//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDMOTC_Auction.WebPortal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NDMOTCAuction_db_devEntities : DbContext
    {
        public NDMOTCAuction_db_devEntities()
            : base("name=NDMOTCAuction_db_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
    }
}
