//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDMOTC_Auction.WebPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> BuyoutPrice { get; set; }
        public Nullable<int> PurchaserId { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
